ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== code-coffee-compendium image:https://img.shields.io/badge/License-MIT-yellow.svg[MIT License, link=https://opensource.org/licenses/MIT] image:https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=flat-square[PRs Welcome, link=http://makeapullrequest.com] image:https://img.shields.io/badge/View%20on-GitHub-orange[View on GitHub, link=https://github.com/LearnTeachCode/code-coffee-compendium/]

image:./logo/code&coffeelogo.svg[logo,246,139]

== Introduction
Welcome to the LearnTeachCode Code & Coffee Compendium Github Repository! Maintained by the Baldwin Park & El Sereno/Alhambra study group, this repository hosts the source code for https://learnteachcode.org/code-coffee-compendium/[code-coffee-compendium] resource site. 

This site was generated using https://asciidoctor.org/[Asciidoctor] - a static-site generator for the https://asciidoctor.org/docs/asciidoc-syntax-quick-reference[AsciiDoc] markup language.

Want extra coding help? Join our https://learnteachcode.org/slack[Slack group].

== Contributing
Contributors are welcome to fork this repository and make changes. Please submit a Pull Request with your changes to be reviewed by a repository owner.

_Not sure where to start?_ There are a number of issues that you can work on. https://github.com/LearnTeachCode/code-coffee-compendium/issues/[Find them here.]


== Dependencies
This project has a number of dependencies that must be met before running on your machine.

1. _Download https://www.ruby-lang.org/en/[Ruby 2.4+]_
2. _Clone or download this repository to your machine._
3. _Open a terminal window. Change your current directory to the cloned project directory._
4. _Install the package bundle by running the following command in the terminal window:_

----
gem install bundler:2.1.4
bundle install
----

This project also uses PlantUML to generate diagrams. https://plantuml.com/download[Download PlantUML here.]

NOTE: In addition to PlantUML, you will need GraphViz to display the sitemap diagram. https://www.graphviz.org/download/[Download GraphViz here.]

== Viewing the Site Locally
CAUTION: Please make sure you have all required dependencies before continuing.

1. _Clone or download this repository to your machine._
2. _Open a terminal window. Change your current directory to the cloned project directory._
3. _Inside of your terminal, type the following command:_

----
ruby convert.rb
----

NOTE: The convert.rb script will convert the .adoc files inside of the project directory into .html files that can be viewed in a web brower. You may see a few warnings appear in the terminal window after running this script. In most cases, it's fine to ignore them. If you have a concern,  https://github.com/LearnTeachCode/code-coffee-compendium/issues/new?assignees=&labels=&template=feature_request.md&title=[please submit an issue.]

Double-click on the index.html file that was generated in the project directory to view the site in a web browser.

== Previewing Changes
If you are a contributor, you can view any changes you have made to the site on your machine by running the following command inside of a terminal window:

----
ruby convert.rb
----

