ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== code-coffee-compendium image:https://img.shields.io/badge/License-MIT-yellow.svg[MIT License, link=https://opensource.org/licenses/MIT] image:https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=flat-square[PRs Welcome, link=http://makeapullrequest.com] image:https://img.shields.io/badge/View%20on-GitHub-orange[View on GitHub, link=https://github.com/LearnTeachCode/code-coffee-compendium/]

https://learnteachcode.org/code-coffee-compendium/home/

== Introduction
Welcome to the LearnTeachCode Code & Coffee Compendium Github Repository! Maintained by the Code & Coffee Office Hours study group, this repository hosts the source code for https://learnteachcode.org/code-coffee-compendium/[code-coffee-compendium] resource site. 

This site was generated using https://asciidoctor.org/[Asciidoctor] - a static-site generator for the https://asciidoctor.org/docs/asciidoc-syntax-quick-reference[AsciiDoc] markup language.

Want extra coding help? Join our https://learnteachcode.org/slack[Slack group].

== Contributing
Contributors are welcome to fork this repository and make changes. Please submit a Pull Request (PR) with your changes to be reviewed by a repository owner.

_Not sure where to start?_ There are a number of issues that you can work on. https://github.com/LearnTeachCode/code-coffee-compendium/issues/[Find them here.]


== Dependencies
This project has a number of dependencies that must be met before running on your machine.

1. Docker
2. Git (for contributors, quicker access to the repository source code)
3. A Bash terminal (standard terminal environment for *nix and macOS).

NOTE: To Windows users: Windows Command Prompt will not satisfy this dependency. Instead, you can use PowerShell or another Bash terminal (like Git Bash for example).

== Viewing the Site Locally
CAUTION: Please make sure you have all required dependencies before continuing.

1. _Clone or download this repository to your machine._
2. _Open a terminal window. Change your current directory to the cloned project directory._
3. _Using a Bash terminal, type the following command:_
   
[source]
---
sh build.sh
---

NOTE: If you receive a permissions error on *nix or macOS, prepend _sudo_ to the command. For example, type the following command:

[source]
---
sudo sh build.sh
---

4. Double-click on the index.html file that was generated in the project directory to view the site in a web browser.

=== Viewing the site through a local web server

There may be situations where you want to view the site locally through a local web server. In this case, rather than running `build.sh` in a Bash terminal, you should run `serve.sh`. For example, type the following command in the project directory:

[source]
---
sh serve.sh
---

After running the `serve.sh` script, you can access the site through your web browser through this URL: http://localhost:1313/code-coffee-compendium

You can stop the local web server by pressing CTRL + C in the Bash terminal where you ran the `serve.sh` script.

