@startuml
hide empty description
discussions -down-> DiscussionsandArticles
discussions -down-> PickingUpaLanguageorFramework
discussions -down-> ChoosingaTextEditororIDE
howto -down-> CommunityHowToGuides
index -down-> Introduction
references -down-> References
references -down-> ProgrammingLanguages
references -down-> Frameworks
references -down-> CommandLine
references -down-> ComputerScienceandMath
references -down-> CareersinTech
sitemap -down-> Sitemap
tutorials -down-> TutorialsandChallenges
tutorials -down-> InteractiveLessons&Challenges
@enduml