@startuml
hide empty description
discussions -down-> DiscussionsandArticles
discussions -down-> PickingUpaLanguageorFramework
discussions -down-> ChoosingaTextEditororIDE
discussions -down-> SoftwareEngineering
discussions -down-> Python
howto -down-> CommunityHowToGuides
howto -down-> Python
howto -down-> OpenSource
index -down-> Introduction
references -down-> References
references -down-> ProgrammingLanguages
references -down-> Frameworks
references -down-> CommandLine
references -down-> ComputerScienceandMath
references -down-> CareersinTech
references -down-> Python
references -down-> PairProgramming
references -down-> SystemDesign
sitemap -down-> Sitemap
tutorials -down-> TutorialsandChallenges
tutorials -down-> InteractiveLessons&Challenges
tutorials -down-> WebDevelopmentTutorials
tutorials -down-> ArtificialIntelligenceandMachineLearningTutorials
tutorials -down-> InformationSecurityTutorials
@enduml